version: "3.8"

services:
  jira:
    container_name: jira
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Database credentials
      spring.datasource.username: ${DB_USERNAME}
      spring.datasource.password: ${DB_PASSWORD}
      spring.datasource.url: jdbc:postgresql://db:5432/jira

      # OAuth credentials
      spring.security.oauth2.client.registration.github.client-id: ${GITHUB_CLIENT_ID}
      spring.security.oauth2.client.registration.github.client-secret: ${GITHUB_CLIENT_SECRET}

      spring.security.oauth2.client.registration.google.client-id: ${GOOGLE_CLIENT_ID}
      spring.security.oauth2.client.registration.google.client-secret: ${GOOGLE_CLIENT_SECRET}

      spring.security.oauth2.client.registration.gitlab.client-id: ${GITLAB_CLIENT_ID}
      spring.security.oauth2.client.registration.gitlab.client-secret: ${GITLAB_CLIENT_SECRET}

      # Mail properties
      spring.mail.username: ${MAIL_USERNAME}
      spring.mail.password: ${MAIL_PASSWORD}

    depends_on:
      - db
      - nginx

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf